sudo: required

services:
  - docker
  - git
  - ssh
  
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
- npm install
- npm test
- echo "Test Güzel Geçti"
- docker build -t emrekeskinmac/node-test:$(echo git rev-parse --short HEAD)
- docker push emrekeskinmac/node-test:$(echo git rev-parse --short HEAD)
- ssh root@46.101.248.17 "docker service update --image emrekeskinmac/node-test:$(echo git rev-parse --short HEAD) test" 
- echo "Oldu"
